<a href="https://colab.research.google.com/github/EstelleYang111/MSSP607/blob/main/Assignments/Participation_Activity_Week6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/MSSP607/Modules/Week06/Student Performance Data.csv')

df.head()

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [3]:
df.shape

(1000, 10)

In [4]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'math score', 'reading score', 'writing score', 'total score',
       'test preparation course', 'admission prospect'],
      dtype='object')

In [5]:
high_performers = lambda data: data.loc[
    data['total score'] >= 240,
    ['gender', 'math score', 'reading score',
     'writing score', 'total score', 'admission prospect']
].copy()

In [6]:
high_score_df = high_performers(df)

high_score_df.head()

,gender,math score,reading score,writing score,total score,admission prospect
1,female,69,90,88,247,high
2,female,90,95,93,278,high
6,female,88,95,92,275,high
16,male,88,89,86,263,high
34,male,97,87,82,266,high

In [7]:
print("Original DataFrame shape:", df.shape)
print("New DataFrame shape:", high_score_df.shape)
print("Minimum total score:", high_score_df['total score'].min())

Original DataFrame shape: (1000, 10)
New DataFrame shape: (198, 6)
Minimum total score: 240

I used a lambda function to create a new DataFrame from the original student performance dataset. The function selects students with a total score of at least 240 and keeps six columns related to their academic performance and admission prospects. This allows me to focus on a smaller group of students while keeping the original dataset unchanged.